# Generated by Django 3.2.6 on 2021-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('chofer', models.CharField(max_length=60)),
                ('capacidad', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_viaje', models.CharField(max_length=25)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('Trabajador', models.ManyToManyField(to='itinerario.Trabajador')),
                ('taxi', models.ManyToManyField(to='itinerario.Taxi')),
            ],
        ),
    ]
