# Generated by Django 3.2.6 on 2021-08-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='taxi',
        ),
        migrations.AddField(
            model_name='viaje',
            name='taxi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itinerario.taxi'),
            preserve_default=False,
        ),
    ]
